spring.application.name=cgl

spring.datasource.url=jdbc:mysql://localhost:3306/laikipia_jobs
spring.datasource.username=root
spring.datasource.password=Bivon@016
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=yourSuperSecretKeyThatIsLongEnoughForHS256Algorithm
jwt.expiration=86400000
